import { initializeApp }                        from "https://www.gstatic.com/firebasejs/12.11.0/firebase-app.js";
import { getDatabase, ref, set, onValue, remove } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-database.js";

// ─── Firebase Config ──────────────────────────────────────────────────────────
const FIREBASE_CONFIG = {
  apiKey:            "AIzaSyBjd4IyQkhKsgvXmlvJ5P8nn4SS8Et6MAw",
    authDomain:        "maptracker-96fdb.firebaseapp.com",
      databaseURL:       "https://maptracker-96fdb-default-rtdb.europe-west1.firebasedatabase.app",
        projectId:         "maptracker-96fdb",
          storageBucket:     "maptracker-96fdb.firebasestorage.app",
            messagingSenderId: "81955613486",
              appId:             "1:81955613486:web:3a7fe4c013c12ac0d6a8bf"
              };

              // ─── Konfiguration ────────────────────────────────────────────────────────────
              const CONFIG = {
                updateIntervalMs: 5000,       // Firebase-Update max. alle 5 Sekunden
                  inactiveAfterMs:  30000,      // Nutzer nach 30s als inaktiv markieren
                    geo: {
                        enableHighAccuracy: true,
                            maximumAge:         3000,
                                timeout:            10000
                                  },
                                    colors: [
                                        "#00e5a0", "#ff4d6d", "#4d8eff", "#ffb340",
                                            "#c084fc", "#34d399", "#fb923c", "#60a5fa"
                                              ]
                                              };

                                              // ─── State ────────────────────────────────────────────────────────────────────
                                              const state = {
                                                userId:     null,
                                                  userColor:  null,
                                                    myPosition: null,
                                                      lastUpdate: 0,
                                                        watchId:    null,
                                                          markers:    {},   // { userId: L.Marker }
                                                            users:      {},   // { userId: { lat, lng, color, timestamp } }
                                                              map:        null,
                                                                db:         null,
                                                                  myRef:      null,
                                                                    usersRef:   null
                                                                    };

                                                                    // ─── DOM ──────────────────────────────────────────────────────────────────────
                                                                    const DOM = {
                                                                      loading:     document.getElementById("loading"),
                                                                        loadingMsg:  document.getElementById("loading-msg"),
                                                                          statusDot:   document.getElementById("status-dot"),
                                                                            statusText:  document.getElementById("status-text"),
                                                                              userBadge:   document.getElementById("user-badge"),
                                                                                onlineCount: document.getElementById("online-count"),
                                                                                  myLat:       document.getElementById("my-lat"),
                                                                                    myLng:       document.getElementById("my-lng"),
                                                                                      myAcc:       document.getElementById("my-acc"),
                                                                                        myTime:      document.getElementById("my-time"),
                                                                                          errorPanel:  document.getElementById("error-panel"),
                                                                                            userList:    document.getElementById("user-list")
                                                                                            };

                                                                                            // ─── Hilfsfunktionen ──────────────────────────────────────────────────────────

                                                                                            function generateId() {
                                                                                              return Math.random().toString(36).substring(2, 9).toUpperCase();
                                                                                              }

                                                                                              function randomColor() {
                                                                                                return CONFIG.colors[Math.floor(Math.random() * CONFIG.colors.length)];
                                                                                                }

                                                                                                function formatTime(ts) {
                                                                                                  return new Date(ts).toLocaleTimeString("de-DE", {
                                                                                                      hour: "2-digit", minute: "2-digit", second: "2-digit"
                                                                                                        });
                                                                                                        }

                                                                                                        function setStatus(type, text) {
                                                                                                          DOM.statusDot.className = type;
                                                                                                            DOM.statusText.textContent = text;
                                                                                                            }

                                                                                                            function showError(msg) {
                                                                                                              DOM.errorPanel.style.display = "block";
  DOM.errorPanel.innerHTML = `⚠ ${msg}`;
}

function showLoadingError(msg) {
  DOM.loading.style.display = "flex";
  DOM.loading.classList.remove("hidden");
  DOM.loadingMsg.textContent = `Fehler beim Laden: ${msg}`;
  setStatus("error", "Fehler beim Laden");
  showError(msg);
}

function hideError() {
  DOM.errorPanel.style.display = "none";
}

function hideLoading() {
  DOM.loading.classList.add("hidden");
  setTimeout(() => DOM.loading.style.display = "none", 600);
}

                                                                                                                      function createMyIcon(color) {
                                                                                                                        return L.divIcon({
                                                                                                                            html: `<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40">
                                                                                                                                  <circle cx="20" cy="20" r="14" fill="${color}" fill-opacity="0.2"/>
                                                                                                                                        <circle cx="20" cy="20" r="8"  fill="${color}"/>
                                                                                                                                              <circle cx="20" cy="20" r="4"  fill="#fff"/>
                                                                                                                                                  </svg>`,
                                                                                                                                                      className: "", iconSize: [40,40], iconAnchor: [20,20], popupAnchor: [0,-24]
                                                                                                                                                        });
                                                                                                                                                        }

                                                                                                                                                        function createUserIcon(color) {
                                                                                                                                                          return L.divIcon({
                                                                                                                                                              html: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                                                                                                                                    <circle cx="16" cy="16" r="10" fill="${color}" fill-opacity="0.25"/>
                                                                                                                                                                          <circle cx="16" cy="16" r="6"  fill="${color}"/>
                                                                                                                                                                                <circle cx="16" cy="16" r="2.5" fill="#fff"/>
                                                                                                                                                                                    </svg>`,
                                                                                                                                                                                        className: "", iconSize: [32,32], iconAnchor: [16,16], popupAnchor: [0,-18]
                                                                                                                                                                                          });
                                                                                                                                                                                          }

                                                                                                                                                                                          // ─── Karte ────────────────────────────────────────────────────────────────────

                                                                                                                                                                                          function initMap() {
  try {
    state.map = L.map("map", { center: [51.1657, 10.4515], zoom: 6 });
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
      attribution: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      maxZoom: 19
    }).addTo(state.map);
  } catch (err) {
    console.error("[Map] Init-Error", err);
    showLoadingError("Karte konnte nicht initialisiert werden. Bitte Seite neu laden.");
    throw err;
  }
}
                                                                                                                                                                                                        // ─── Marker-Verwaltung ────────────────────────────────────────────────────────

                                                                                                                                                                                                        function upsertMarker(userId, lat, lng, color, isMe) {
                                                                                                                                                                                                          const latlng = L.latLng(lat, lng);
                                                                                                                                                                                                            const icon   = isMe ? createMyIcon(color) : createUserIcon(color);
                                                                                                                                                                                                              const label  = isMe ? `Ich (${userId})` : `Nutzer ${userId}`;

                                                                                                                                                                                                                if (state.markers[userId]) {
                                                                                                                                                                                                                    state.markers[userId].setLatLng(latlng);
                                                                                                                                                                                                                        state.markers[userId].setIcon(icon);
                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                              const marker = L.marker(latlng, { icon }).addTo(state.map);
                                                                                                                                                                                                                                  marker.bindPopup(buildPopup(label, color, lat, lng, Date.now()));
                                                                                                                                                                                                                                      state.markers[userId] = marker;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                        function buildPopup(label, color, lat, lng, ts) {
                                                                                                                                                                                                                                          return `<b style="color:${color}">${label}</b><br/>
                                                                                                                                                                                                                                              <span style="opacity:.7">Lat:</span> ${lat.toFixed(5)}<br/>
                                                                                                                                                                                                                                                  <span style="opacity:.7">Lng:</span> ${lng.toFixed(5)}<br/>
                                                                                                                                                                                                                                                      <span style="opacity:.7">Zeit:</span> ${formatTime(ts)}`;
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                      function removeMarker(userId) {
                                                                                                                                                                                                                                                        if (state.markers[userId]) {
                                                                                                                                                                                                                                                            state.map.removeLayer(state.markers[userId]);
                                                                                                                                                                                                                                                                delete state.markers[userId];
                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                  // ─── Sidebar ──────────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                  function renderUserList() {
                                                                                                                                                                                                                                                                    const now = Date.now();
                                                                                                                                                                                                                                                                      const sorted = Object.entries(state.users).sort(([a]) => a === state.userId ? -1 : 1);

                                                                                                                                                                                                                                                                        DOM.userList.innerHTML = "";

                                                                                                                                                                                                                                                                          let activeCount = 0;
                                                                                                                                                                                                                                                                            for (const [uid, data] of sorted) {
                                                                                                                                                                                                                                                                                if (now - data.timestamp > CONFIG.inactiveAfterMs) continue;
                                                                                                                                                                                                                                                                                    activeCount++;
                                                                                                                                                                                                                                                                                        const isMe = uid === state.userId;

                                                                                                                                                                                                                                                                                            const card = document.createElement("div");
                                                                                                                                                                                                                                                                                                card.className = `user-card${isMe ? " is-me" : ""}`;
                                                                                                                                                                                                                                                                                                    card.innerHTML = `
                                                                                                                                                                                                                                                                                                          <div class="user-card-top">
                                                                                                                                                                                                                                                                                                                  <div class="user-avatar" style="background:${data.color}">${uid.charAt(0)}</div>
                                                                                                                                                                                                                                                                                                                          <div class="user-name" style="color:${data.color}">${isMe ? "Ich" : "Nutzer"} · ${uid}</div>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                      <div class="user-meta">
                                                                                                                                                                                                                                                                                                                                              <span><span>LAT</span><span class="ml">${data.lat.toFixed(5)}</span></span>
                                                                                                                                                                                                                                                                                                                                                      <span><span>LNG</span><span class="ml">${data.lng.toFixed(5)}</span></span>
                                                                                                                                                                                                                                                                                                                                                              <span style="grid-column:1/-1"><span>ZULETZT</span><span class="ml">${formatTime(data.timestamp)}</span></span>
                                                                                                                                                                                                                                                                                                                                                                    </div>`;
                                                                                                                                                                                                                                                                                                                                                                        card.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                              state.map.flyTo([data.lat, data.lng], 15, { duration: 1.2 });
                                                                                                                                                                                                                                                                                                                                                                                    state.markers[uid]?.openPopup();
                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                            DOM.userList.appendChild(card);
                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                DOM.onlineCount.textContent = `${activeCount} online`;
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                // ─── Firebase ─────────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                function uploadPosition(lat, lng, accuracy) {
                                                                                                                                                                                                                                                                                                                                                                                                  const now = Date.now();
                                                                                                                                                                                                                                                                                                                                                                                                    if (now - state.lastUpdate < CONFIG.updateIntervalMs) return;
                                                                                                                                                                                                                                                                                                                                                                                                      state.lastUpdate = now;

                                                                                                                                                                                                                                                                                                                                                                                                        set(state.myRef, {
                                                                                                                                                                                                                                                                                                                                                                                                            latitude:  lat,
                                                                                                                                                                                                                                                                                                                                                                                                                longitude: lng,
                                                                                                                                                                                                                                                                                                                                                                                                                    accuracy:  Math.round(accuracy),
                                                                                                                                                                                                                                                                                                                                                                                                                        timestamp: now,
                                                                                                                                                                                                                                                                                                                                                                                                                            color:     state.userColor,
                                                                                                                                                                                                                                                                                                                                                                                                                                userId:    state.userId
                                                                                                                                                                                                                                                                                                                                                                                                                                  }).catch(err => console.error("[Firebase] Upload:", err));
                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                  function watchAllUsers() {
                                                                                                                                                                                                                                                                                                                                                                                                                                    onValue(state.usersRef, snapshot => {
    const data = snapshot.val() || {};

    // Entfernte Nutzer löschen
    for (const uid of Object.keys(state.markers)) {
      if (!data[uid]) { removeMarker(uid); delete state.users[uid]; }
    }

    // Alle Nutzer aktualisieren
    for (const [uid, entry] of Object.entries(data)) {
      const isMe  = uid === state.userId;
      const color = entry.color || "#4d8eff";
      state.users[uid] = { lat: entry.latitude, lng: entry.longitude, color, timestamp: entry.timestamp || Date.now() };
      upsertMarker(uid, entry.latitude, entry.longitude, color, isMe);

      // Popup-Text aktualisieren
      const label = isMe ? `Ich (${uid})` : `Nutzer ${uid}`;
      state.markers[uid]?.setPopupContent(buildPopup(label, color, entry.latitude, entry.longitude, entry.timestamp));
    }

    renderUserList();
  }, err => {
    console.error("[Firebase] watchAllUsers Fehler", err);
    showLoadingError("Firebase-Daten konnten nicht geladen werden: " + (err.message || err));
  });
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ─── Geolocation ──────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function startGeolocation() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!navigator.geolocation) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            showError("Geolocation wird von diesem Browser nicht unterstützt.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setStatus("error", "Geolocation nicht verfügbar");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    hideLoading();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            state.watchId = navigator.geolocation.watchPosition(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onPositionUpdate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPositionError,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CONFIG.geo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function onPositionUpdate(pos) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const { latitude: lat, longitude: lng, accuracy } = pos.coords;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              hideError();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setStatus("active", "Live · Standort wird übertragen");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  upsertMarker(state.userId, lat, lng, state.userColor, true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    DOM.myLat.textContent  = lat.toFixed(5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      DOM.myLng.textContent  = lng.toFixed(5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        DOM.myAcc.textContent  = `±${Math.round(accuracy)} m`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          DOM.myTime.textContent = formatTime(Date.now());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!state.myPosition) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                state.map.flyTo([lat, lng], 14, { duration: 2 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state.myPosition = { lat, lng };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      uploadPosition(lat, lng, accuracy);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hideLoading();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function onPositionError(err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const msgs = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [err.PERMISSION_DENIED]:    "Standortzugriff verweigert. Bitte im Browser erlauben.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [err.POSITION_UNAVAILABLE]: "Standort nicht verfügbar. GPS oder WLAN aktivieren.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [err.TIMEOUT]:              "Standortabfrage Timeout. Seite neu laden."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          showError(msgs[err.code] || `Fehler: ${err.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setStatus("error", "Standortfehler");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              hideLoading();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // ─── Cleanup ──────────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function cleanup() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (state.myRef) remove(state.myRef).catch(() => {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (state.watchId !== null) navigator.geolocation.clearWatch(state.watchId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

window.addEventListener("error", event => {
  console.error("[Global] Fehler", event.error || event.message);
  showLoadingError(event.message || "Unbekannter Fehler");
});

window.addEventListener("unhandledrejection", event => {
  console.error("[Global] Unerwartete Promise-Rejection", event.reason);
  const reason = event.reason?.message || String(event.reason);
  showLoadingError("Unerwarteter Fehler: " + reason);
});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ─── Init ─────────────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async function init() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state.userId    = generateId();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      state.userColor = randomColor();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        DOM.userBadge.textContent = state.userId;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          DOM.loadingMsg.textContent = "Initialisiere Karte…";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            initMap();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              DOM.loadingMsg.textContent = "Verbinde mit Firebase…";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const app    = initializeApp(FIREBASE_CONFIG);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        state.db       = getDatabase(app);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            state.usersRef = ref(state.db, "users");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                state.myRef    = ref(state.db, `users/${state.userId}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Verbindungsstatus beobachten
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const connRef = ref(state.db, ".info/connected");
      onValue(connRef, snap => {
        if (snap.val()) {
          setStatus("active", "Verbunden · Live");
          hideError();
        } else {
          setStatus("", "Verbindung unterbrochen…");
          showError("Verbindung zu Firebase verloren. Warte auf Wiederherstellung...");
        }
      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                watchAllUsers();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    window.addEventListener("beforeunload", cleanup);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
        showLoadingError(`Firebase Fehler: ${err.message}`);
        setStatus("error", "Firebase nicht verbunden");
        console.error("[Firebase]", err);
      }

      DOM.loadingMsg.textContent = "Starte Geolocation…";
      startGeolocation();
    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        init();
